#!/bin/bash
# Copy file path

if [[ -n $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS ]]; then
	head -1 <<< "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" \
		| xclip -selection clipboard -rmlastnl \
	&& notify-send "Path Copied!" \
		"Path: <i>$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS</i>" \
		--icon=insert-link-symbolic \
		--hint=int:transient:1 \
	|| msg='Path NOT Copied'
else
	msg='Path NOT Extracted'
fi

[[ -n "$msg" ]] && showosd network-offline-symbolic --label "$msg"
